/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as LoginImport } from './routes/login';
import { Route as DashboardImport } from './routes/dashboard';
import { Route as DashboardMeImport } from './routes/dashboard/me';
import { Route as DashboardMePostImport } from './routes/dashboard/me/post';

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any);

const DashboardMeRoute = DashboardMeImport.update({
  path: '/me',
  getParentRoute: () => DashboardRoute,
} as any);

const DashboardMePostRoute = DashboardMePostImport.update({
  path: '/post',
  getParentRoute: () => DashboardMeRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard/me': {
      id: '/dashboard/me';
      path: '/me';
      fullPath: '/dashboard/me';
      preLoaderRoute: typeof DashboardMeImport;
      parentRoute: typeof DashboardImport;
    };
    '/dashboard/me/post': {
      id: '/dashboard/me/post';
      path: '/post';
      fullPath: '/dashboard/me/post';
      preLoaderRoute: typeof DashboardMePostImport;
      parentRoute: typeof DashboardMeImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  DashboardRoute: DashboardRoute.addChildren({
    DashboardMeRoute: DashboardMeRoute.addChildren({ DashboardMePostRoute }),
  }),
  LoginRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dashboard",
        "/login"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/me"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/dashboard/me": {
      "filePath": "dashboard/me.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/me/post"
      ]
    },
    "/dashboard/me/post": {
      "filePath": "dashboard/me/post.tsx",
      "parent": "/dashboard/me"
    }
  }
}
ROUTE_MANIFEST_END */
